language: php

php:
  - 5.5
  - 5.6

install:
  - composer self-update
  - git clone -q --depth=1 https://github.com/phalcon/cphalcon.git
  - (cd cphalcon/ext; export CFLAGS="-g3 -O1 -fno-delete-null-pointer-checks -Wall"; phpize &> /dev/null && ./configure --silent --enable-phalcon &> /dev/null && make --silent -j4 > /dev/null && make --silent install && phpenv config-add ../unit-tests/ci/phalcon.ini &> /dev/null)
  - php -r 'echo \Phalcon\Version::get() . PHP_EOL;'
  - composer install --prefer-source --no-interaction

script:
  - php vendor/bin/phpc
  - php vendor/bin/phpunit