language: php

php:
  - 5.5
  - 5.6

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
    - $HOME/cphalcon
    - $HOME/pci

before_install:
  - curl -sS https://raw.githubusercontent.com/techpivot/phalcon-ci-installer/master/bin/install-phalcon.sh | sh
  - php -r 'echo \Phalcon\Version::get() . PHP_EOL;'
  - composer install --prefer-source --no-interaction

script:
  - php vendor/bin/phpcs
  - php vendor/bin/phpunit