language: php

php:
  - 5.5
  - 5.6

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
    - $HOME/cphalcon
    - $HOME/pci

before_install:
  - test -d $HOME/pci || wget https://github.com/techpivot/phalcon-ci-installer/archive/master.zip && unzip master.zip -d $HOME/pci
  - $HOME/pci/phalcon-ci-installer/bin/install-phalcon.sh
  - php -r 'echo \Phalcon\Version::get() . PHP_EOL;'
  - composer install --prefer-source --no-interaction

script:
  - php vendor/bin/phpcs
  - php vendor/bin/phpunit