language: php

php:
  - 5.5
  - 5.6

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
    - $HOME/cphalcon

before_install:
  - vendor/bin/install-phalcon.sh
  - php -r 'echo \Phalcon\Version::get() . PHP_EOL;'
  - composer install --prefer-source --no-interaction

script:
  - php vendor/bin/phpcs
  - php vendor/bin/phpunit